services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1000:1000 # adjust
    ports:
      - "8080:80"
    volumes:
      - ./srv:/srv # files will be stored here
      - ./filebrowser.db:/database.db # users info/settings will be stored here
      - ./filebrowser.json:/.filebrowser.json # config file
    restart: always

# In the same location create an/a
# 1.empty file filebrowser.db
# 2.folder and rename it to srv
# 3.file filebrowser.json and paste below content in it
  # {     "port": 80,     "baseURL": "",     "address": "",     "log": "stdout",     "database": "/database.db",     "root": "/srv" }
# 4.Now start the docker
  # docker compose up -d

# default username: admin
# password: admin