services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local  # Change this to your WSL2 hostname or IP
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://172.19.184.55'
    ports:
      - "172.19.184.55:8929:80"    # Web UI
      - "172.19.184.55:443:443"    # HTTPS (optional, can be omitted for testing)
      - "172.19.184.55:2222:22"    # SSH
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    restart: always

# external_url 'http://<YOUR_WSL2_IP>'