services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.69:8929'
    ports:
      - '192.168.1.69:8929:8929'          # HTTP
      - '192.168.1.69:443:443'          # HTTPS
      - '192.168.1.69:22:22'            # SSH
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    restart: always

# external_url 'http://hostip:8929'
