
services:
  jenkins:
    image: jenkins/jenkins:2.479.1-jdk17
    container_name: jenkins-master
    privileged: true
    ports:
      - "8082:8080"    # Expose Jenkins on port 8082 (default port of jenkins in docker is 8080) 
      - "50000:50000"  # Port for Jenkins agents to connect
    volumes:
      - ./jenkins_home:/var/jenkins_home  # Persistent storage for Jenkins data (on host machine)
    restart: always

# for getting initial password
# docker exec -it jenkins-master cat /var/jenkins_home/secrets/initialAdminPassword