services:
  postgres:
    image: postgres:15
    container_name: postgres_rpi
    restart: unless-stopped
    environment:
      POSTGRES_USER: pi
      POSTGRES_PASSWORD: raspberrypi
      POSTGRES_DB: pi_database
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: "0.5"