services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    ports:
      - "27017:27017" # Expose MongoDB port to the host
    volumes:
      - ./mongodb_data:/data/db # Persist MongoDB data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # Admin username
      MONGO_INITDB_ROOT_PASSWORD: password123 # Admin password
    restart: always # Automatically restart on failure

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - "8081:8081" # Expose the mongo-express interface on the host
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin # MongoDB admin username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123 # MongoDB admin password
      ME_CONFIG_MONGODB_SERVER: mongodb # Name of the MongoDB service
      ME_CONFIG_BASICAUTH_USERNAME: mongodb
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongodb # Ensure mongo-express starts after MongoDB
    restart: always # Automatically restart on failure
